# Generated by Django 5.2.7 on 2025-10-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='extra_info',
            field=models.CharField(default='', max_length=50),
        ),
    ]
